### PR TITLE
Issue #221. Testing the idea of hiding the elements that aren't editable...

### PR DESCRIPTION
**Pull request by marcelomazza**
....

### CODE REVIEW

**Comment by marcelomazza** [comment]
BTW I just realised this needs to get added the correct prefixes, I'll update later.

**Comment by iseulde** [comment]
No need to prefix. We can autoprefix. :)

**Comment by marcelomazza** [comment]
>  Why __wp-uploader-id?

Because it doesn't have the .wp-core-ui. Appears when you click on "Add featured image":

```
<div tabindex="0" id="__wp-uploader-id-2" class="supports-drag-drop" style="position: relative;">
		<div class="media-modal wp-core-ui">
```

**Comment by iseulde** [comment]
Let's close this PR and discuss implementation further in #223.

**Pull request closed without merging**
